// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8NxdQXewlWxV2OPzJyfIfcQYKJxnP8dQ',
    appId: '1:762392319174:web:7f4ee42967d5d2ac2d33c7',
    messagingSenderId: '762392319174',
    projectId: 'pomodoro-ea59c',
    authDomain: 'pomodoro-ea59c.firebaseapp.com',
    storageBucket: 'pomodoro-ea59c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NxdQXewlWxV2OPzJyfIfcQYKJxnP8dQ',
    appId: '1:762392319174:android:7f4ee42967d5d2ac2d33c7',
    messagingSenderId: '762392319174',
    projectId: 'pomodoro-ea59c',
    storageBucket: 'pomodoro-ea59c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NxdQXewlWxV2OPzJyfIfcQYKJxnP8dQ',
    appId: '1:762392319174:ios:7f4ee42967d5d2ac2d33c7',
    messagingSenderId: '762392319174',
    projectId: 'pomodoro-ea59c',
    iosBundleId: 'com.pomodoro.tanjil',
    storageBucket: 'pomodoro-ea59c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8NxdQXewlWxV2OPzJyfIfcQYKJxnP8dQ',
    appId: '1:762392319174:ios:7f4ee42967d5d2ac2d33c7',
    messagingSenderId: '762392319174',
    projectId: 'pomodoro-ea59c',
    iosBundleId: 'com.pomodoro.tanjil',
    storageBucket: 'pomodoro-ea59c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8NxdQXewlWxV2OPzJyfIfcQYKJxnP8dQ',
    appId: '1:762392319174:web:7f4ee42967d5d2ac2d33c7',
    messagingSenderId: '762392319174',
    projectId: 'pomodoro-ea59c',
    authDomain: 'pomodoro-ea59c.firebaseapp.com',
    storageBucket: 'pomodoro-ea59c.firebasestorage.app',
  );
}
